#!/bin/sh
# Generated by Linux Your Way (lyw) — REVIEW BEFORE RUNNING.
# Build model: hybrid (binary base from real repos + local builds).
# Config: uefi + glibc + gnu + bash + dinit + xbps + lts + precompiled + gcc + zstd + modules + separate + gnu + compat + none + grub + off + ext4 + none + dhcpcd + password + doas + selinux + hybrid
# [incompatible] SELinux needs rebuilt/labeled packages; only Gentoo has real support
# [manual-config-needed] Void is runit-native; dinit service files must be written by hand
echo 'INCOMPATIBLE combination — fix the config in lyw first.' >&2
exit 1

set -eu

# Set DISK=/dev/sdX in the environment to skip all questions and
# WIPE that whole disk (automation/testing path).
ROOT="${ROOT:-/mnt/lyw}"
JOBS="${JOBS:-$(nproc)}"
SCRIPTDIR=$(cd "$(dirname "$0")" && pwd)
mkdir -p "$ROOT"

msg() { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }

CHROOT="${CHROOT:-xchroot}"
# fall back to plain chroot (+ prep_chroot mounts) if the helper is absent
command -v "$CHROOT" >/dev/null 2>&1 || CHROOT=chroot
REPO=https://repo-default.voidlinux.org/current
XARCH=x86_64

cmdline() {
  printf 'root=UUID=%s rw' "$(blkid -s UUID -o value "$ROOTP")"
}

check_net() {
  msg 'Checking internet connectivity'
  while ! curl -sm8 -o /dev/null https://www.google.com 2>/dev/null && \
        ! wget -q -T8 -O /dev/null https://www.google.com 2>/dev/null; do
    echo 'No internet connection (packages must be downloaded).'
    if command -v nmtui >/dev/null 2>&1; then
      printf 'Open nmtui to connect now? [Y/n] '; read -r a
      case "$a" in n|N) ;; *) nmtui ;; esac
    else
      echo 'Connect manually (ip link / dhcpcd / iwctl / wpa_supplicant),'
      printf 'then press Enter to re-check... '; read -r a
    fi
  done
}

pkg() {
  XBPS_ARCH=$XARCH xbps-install -y -r "$ROOT" -R "$REPO" "$@"
}

svc_enable() {  # enable services at boot
  for s in "$@"; do
    echo "NOTE: write a dinit service for $s and enable it after boot" >&2
  done
}

devpath() { case "$1" in /dev/*) printf '%s\n' "$1";; *) printf '/dev/%s\n' "$1";; esac; }

by_partlabel() { blkid -o device -t PARTLABEL="$1" | grep -F "$DISK" | tail -1; }

confirm_target() {
  echo; echo 'Install target:'
  if [ "$WIPE" = 1 ]; then
    echo "  the WHOLE disk $DISK will be WIPED"
  else
    [ -z "${ESP:-}" ] || echo "  ESP:  $ESP ($([ "$FORMAT_ESP" = 1 ] && echo formatted || echo 'kept as-is'))"
    echo "  root: $ROOTP (FORMATTED — everything on it is lost)"
  fi
  printf 'Proceed? Type YES: '; read -r ok
  [ "$ok" = YES ] || exit 1
}

pick_parts() {
  WIPE=0; FORMAT_ESP=0
  lsblk -o NAME,SIZE,FSTYPE,PARTTYPENAME,PARTLABEL,MOUNTPOINTS "$DISK"
  printf 'EFI system partition (kept as-is, e.g. %s1): ' "$DISK"; read -r a
  ESP=$(devpath "$a"); [ -b "$ESP" ] || { echo "not a partition: $ESP" >&2; exit 1; }
  printf 'Root partition (WILL be formatted): '; read -r a
  ROOTP=$(devpath "$a"); [ -b "$ROOTP" ] || { echo "not a partition: $ROOTP" >&2; exit 1; }
}

free_space() {
  WIPE=0
  [ "$(blkid -s PTTYPE -o value "$DISK")" = gpt ] || {
    echo 'Free-space install needs a GPT disk. Use existing parts or whole-disk.' >&2; exit 1; }
  ESP=$(lsblk -nlo PATH,PARTTYPE "$DISK" \
    | awk '$2=="c12a7328-f81f-11d2-ba4b-00a0c93ec93b"{print $1; exit}')
  if [ -n "$ESP" ]; then
    FORMAT_ESP=0; echo "Reusing existing EFI partition: $ESP"
  else
    FORMAT_ESP=1
    sgdisk -n0:0:+512M -t0:ef00 -c0:lyw-esp "$DISK"
    partprobe "$DISK"; sleep 1
    ESP=$(by_partlabel lyw-esp)
  fi
  sgdisk -n0:0:0 -t0:8300 -c0:lyw-root "$DISK"   # takes the largest free block
  partprobe "$DISK"; sleep 1
  ROOTP=$(by_partlabel lyw-root)
  [ -n "$ROOTP" ] || { echo 'could not create a root partition — no free space?' >&2; exit 1; }
}

shrink() {
  lsblk -o NAME,SIZE,FSTYPE,FSUSED,PARTLABEL "$DISK"
  printf 'Partition to SHRINK (data is kept, but BACK IT UP first): '; read -r a
  SP=$(devpath "$a"); [ -b "$SP" ] || { echo "not a partition: $SP" >&2; exit 1; }
  T=$(blkid -s TYPE -o value "$SP")
  printf 'New total size for %s in GiB (must exceed its used space): ' "$SP"; read -r G
  printf 'Shrink %s (%s) to %s GiB? Type YES: ' "$SP" "$T" "$G"; read -r ok
  [ "$ok" = YES ] || exit 1
  case "$T" in
  ext4) e2fsck -f "$SP"; resize2fs "$SP" "${G}G" ;;
  ntfs) ntfsresize --no-action --size "${G}G" "$SP"   # dry run aborts if unsafe
        ntfsresize --force --size "${G}G" "$SP" ;;
  *) echo "can only shrink ext4 or ntfs (found: ${T:-nothing})" >&2; exit 1 ;;
  esac
  PN=$(cat "/sys/class/block/$(basename "$SP")/partition")
  START=$(sgdisk -i "$PN" "$DISK" | awk '/First sector/{print $3}')
  TGUID=$(sgdisk -i "$PN" "$DISK" | awk '/Partition GUID code:/{print $4}')
  PGUID=$(sgdisk -i "$PN" "$DISK" | awk '/Partition unique GUID:/{print $4}')
  # recreate the entry at the same start, smaller; GUIDs preserved so boot
  # entries keep working (a Windows partition gets a chkdsk on next boot)
  sgdisk -d "$PN" -n "$PN:$START:+${G}G" -t "$PN:$TGUID" -u "$PN:$PGUID" "$DISK"
  partprobe "$DISK"; sleep 1
}

choose_target() {
  FORMAT_ESP=1; WIPE=1
  if [ -n "${DISK:-}" ]; then
    # non-interactive: DISK given in the environment — whole disk, no questions
    case "$DISK" in *[0-9]) P="${DISK}p";; *) P="$DISK";; esac
    ESP="${P}1"; ROOTP="${P}2"
    confirm_target; return
  fi
  msg 'Install target'
  lsblk -d -e7 -o NAME,SIZE,MODEL,TRAN
  printf 'Disk (e.g. sda, nvme0n1): '; read -r a; DISK=$(devpath "$a")
  [ -b "$DISK" ] || { echo "not a block device: $DISK" >&2; exit 1; }
  case "$DISK" in *[0-9]) P="${DISK}p";; *) P="$DISK";; esac
  cat <<'MENU'
How should this disk be used?
  1) Whole disk      WIPE EVERYTHING and auto-partition (simplest)
  2) Free space      keep existing OSes, install into unallocated space (dual-boot)
  3) Existing parts  you already made partitions; pick them
  4) Shrink first    shrink an ext4/NTFS partition to make room (dual-boot)
  5) cfdisk          edit the partition table yourself, then pick partitions
MENU
  printf 'Choice [1-5]: '; read -r m
  case "$m" in
  1) WIPE=1; ESP="${P}1"; ROOTP="${P}2" ;;
  2) free_space ;;
  3) pick_parts ;;
  4) shrink; free_space ;;
  5) cfdisk "$DISK"; partprobe "$DISK"; sleep 1; pick_parts ;;
  *) echo 'no such option' >&2; exit 1 ;;
  esac
  confirm_target
}

partition() {
  if [ "$WIPE" = 1 ]; then
    msg "Partitioning $DISK (GPT: 512M EFI + root)"
    sgdisk --zap-all "$DISK"
    sgdisk -n1:0:+512M -t1:ef00 -c1:EFI -n2:0:0 -t2:8300 -c2:lyw-root "$DISK"
    partprobe "$DISK"; sleep 1
  fi
  ROOTDEV="$ROOTP"
  if [ "$FORMAT_ESP" = 1 ]; then mkfs.fat -F32 "$ESP"; fi
  mkfs.ext4 -F -L lyw-root "$ROOTDEV"
  mount "$ROOTDEV" "$ROOT"
  mkdir -p "$ROOT/boot/efi"
  mount "$ESP" "$ROOT/boot/efi"
}

base_install() {
  msg 'Base: Void via xbps-install'
  command -v xbps-install >/dev/null 2>&1 || {
    msg 'xbps not on this host: fetching static xbps'
    mkdir -p /tmp/lyw-xbps
    curl -L https://repo-default.voidlinux.org/static/xbps-static-latest.x86_64-musl.tar.xz \
      | tar -xJ -C /tmp/lyw-xbps
    PATH=/tmp/lyw-xbps/usr/bin:$PATH
  }
  XBPS_ARCH=$XARCH xbps-install -Sy -r "$ROOT" -R "$REPO" base-system
  cp /etc/resolv.conf "$ROOT/etc/"
}

prep_chroot() {
  mount --rbind /dev "$ROOT/dev";  mount --make-rslave "$ROOT/dev"
  mount -t proc proc "$ROOT/proc"
  mount --rbind /sys "$ROOT/sys";  mount --make-rslave "$ROOT/sys"
}

kernel_install() {
  msg 'Kernel: linux-lts (precompiled)'
  pkg linux-lts
}

graphics_install() {
  msg 'Graphics: none (TTY only)'
}

network_install() {
  msg 'Network: dhcpcd'
  pkg dhcpcd
  svc_enable dhcpcd
}

bootloader_install() {
  msg 'Bootloader: GRUB'
  pkg grub-x86_64-efi os-prober
  # dual-boot: let grub-mkconfig find other installed systems
  mkdir -p "$ROOT/etc/default"
  echo 'GRUB_DISABLE_OS_PROBER=false' >> "$ROOT/etc/default/grub"
  echo 'GRUB_TIMEOUT=3' >> "$ROOT/etc/default/grub"
  $CHROOT "$ROOT" grub-install --target=x86_64-efi \
    --efi-directory=/boot/efi --bootloader-id=LYW
  $CHROOT "$ROOT" grub-mkconfig -o /boot/grub/grub.cfg
}

toolchain_install() {
  msg 'Toolchain: GCC + Binutils (compat profile)'
  pkg gcc make binutils git
  printf 'CFLAGS="-O2 -pipe"\nCXXFLAGS="-O2 -pipe"\n' > "$ROOT/etc/lyw-build.conf"
}

security_install() {
  msg 'Security: SELinux'
  echo 'MANUAL: SELinux — switch the Gentoo profile, emerge policies, set'
  echo 'SELINUX=permissive in /etc/selinux/config, relabel with rlpkg -a -r.'
}

locale_time() {
  msg 'Timezone, clock, locale, keymap'
  TZSEL='Europe/Bucharest'
  if [ -e "$ROOT/usr/share/zoneinfo/$TZSEL" ]; then
    ln -sf "../usr/share/zoneinfo/$TZSEL" "$ROOT/etc/localtime"
  else
    echo "NOTE: timezone $TZSEL not found in the target; set /etc/localtime yourself" >&2
  fi
  $CHROOT "$ROOT" hwclock --systohc 2>/dev/null || true
  KM='us'
  printf 'KEYMAP=%s\n' "$KM" > "$ROOT/etc/vconsole.conf"
  sed -i "s/^#\\?KEYMAP=.*/KEYMAP=$KM/" "$ROOT/etc/rc.conf" || true
  LOC='en_US.UTF-8'
  printf 'LANG=%s\n' "$LOC" > "$ROOT/etc/locale.conf"
  echo "$LOC UTF-8" >> "$ROOT/etc/default/libc-locales"
  $CHROOT "$ROOT" xbps-reconfigure -f glibc-locales || true
}

users_setup() {
  msg 'Shell, users, passwords'
  pkg bash
  SH=$($CHROOT "$ROOT" sh -c 'command -v bash' || true)
  if [ -n "$SH" ]; then
    sed -i "s#^root:\\(.*\\):[^:]*\$#root:\\1:$SH#" "$ROOT/etc/passwd"
  else
    echo 'NOTE: bash not found in target; root keeps /bin/sh' >&2
  fi
  echo 'Set a root password: '"$CHROOT"' "$ROOT" passwd'
  pkg opendoas
  printf 'permit persist :wheel\n' > "$ROOT/etc/doas.conf"
  chmod 640 "$ROOT/etc/doas.conf"
}

branding_install() {
  msg 'Branding: Linux Your Way'
  # /etc/os-release as a regular file wins over /usr/lib/os-release
  rm -f "$ROOT/etc/os-release"
  {
    printf 'NAME="Linux Your Way"\n'
    printf 'PRETTY_NAME="Linux Your Way"\n'
    printf 'ID=lyw\n'
    printf 'ID_LIKE="void"\n'
    printf 'BUILD_ID=rolling\n'
    printf 'ANSI_COLOR="1;33"\n'
    printf 'HOME_URL="https://github.com/Vifuddyxg/linux-your-way"\n'
    printf 'LOGO=lyw\n'
  } > "$ROOT/etc/os-release"
  printf 'Linux Your Way \\r (\\l)\n\n' > "$ROOT/etc/issue"
  mkdir -p "$ROOT/usr/share/lyw" "$ROOT/etc/fastfetch"
  # the letter-art logo ships on the LYW live ISO; copy it into the target
  if [ -f /usr/share/lyw/logo.txt ]; then
    cp /usr/share/lyw/logo.txt "$ROOT/usr/share/lyw/logo.txt"
    cat > "$ROOT/etc/fastfetch/config.jsonc" <<'EOF'
// Linux Your Way — letter-art logo (see github.com/Vifuddyxg/linux-your-way)
{
    "logo": {
        "type": "file-raw",
        "source": "/usr/share/lyw/logo.txt",
        "padding": { "right": 3 }
    }
}
EOF
  else
    echo 'NOTE: /usr/share/lyw/logo.txt not on this host; fastfetch logo skipped' >&2
  fi
}

system_config() {
  msg 'System configuration'
  echo 'lyw' > "$ROOT/etc/hostname"
  printf '127.0.0.1 localhost\n127.0.1.1 lyw\n' >> "$ROOT/etc/hosts"
  {
    printf 'UUID=%s / ext4 defaults 0 1\n' "$(blkid -s UUID -o value "$ROOTP")"
    printf 'UUID=%s /boot/efi vfat defaults 0 2\n' "$(blkid -s UUID -o value "$ESP")"
  } >> "$ROOT/etc/fstab"
}

check_net
choose_target
partition
base_install
if [ "$CHROOT" = chroot ]; then prep_chroot; fi
cp -L /etc/resolv.conf "$ROOT/etc/resolv.conf" 2>/dev/null || true
kernel_install
graphics_install
network_install
bootloader_install
toolchain_install
security_install
locale_time
users_setup
branding_install
system_config
msg 'Done. Review $ROOT, then reboot.'
